# Generated by Django 3.1.7 on 2021-06-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homework_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homework',
            new_name='allhomeworks',
        ),
        migrations.AlterModelOptions(
            name='allhomeworks',
            options={'verbose_name': 'homework'},
        ),
    ]
