# Generated by Django 3.1.7 on 2021-07-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210626_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allhomeworks',
            name='img',
        ),
        migrations.AddField(
            model_name='allhomeworks',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
